#!/bin/bash

# rory.hunter@blackpepper.co.uk Thu Jul  2 09:22:33 BST 2015 
#
# This wrapper throws away the container when it shuts down. To access
# files on your actual filesystem, mount a volume when you run the script
# e.g. 
#
# idea -v $HOME/projects:/home/dev/projects
#
# Note that application-specific files are mounted in the diretory below.
# You can more or remove it to reset the application.

CONTAINER_NAME=idea
SETTINGS_DIR="$HOME/idea"

docker ps | awk 'NR > 1 {print $NF}' | grep -q $CONTAINER_NAME

if [ $? -eq 0 ]; then
	echo "$CONTAINER_NAME is already running." >&2
	exit 1
fi

# Check for an existing container
docker ps -a | awk 'NR > 1 {print $NF}' | grep -q $CONTAINER_NAME

if [ $? -eq 0 ]; then
	docker start $CONTAINER_NAME
else
	if [ ! -d "$SETTINGS_DIR" ]; then
		mkdir "$SETTINGS_DIR"
	fi

	docker run \
		-d \
		--user="$UID" \
		-v /tmp/.X11-unix:/tmp/.X11-unix \
		-v "$SETTINGS_DIR":/home/dev/ \
		--net host \
		-e DISPLAY="$DISPLAY" \
		--name $CONTAINER_NAME \
		"$@" \
		blackpepper/idea
fi
